name: 'my first container action'
description: 'testing'
author: 'Obaid'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Awesome'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
